// packages/react/src/lyric-player.tsx
import {
	LyricPlayer as CoreLyricPlayer,
	type LyricLineMouseEvent,
	type LyricLine,
	type spring,
} from "@applemusic-like-lyrics/core";
import {
	useRef,
	useEffect,
	forwardRef,
	useImperativeHandle,
	type HTMLProps,
	type ReactNode,
} from "react";
import { createPortal } from "react-dom";

/**
 * 歌词播放组件的属性
 */
export interface LyricPlayerProps {
	/**
	 * 是否禁用歌词播放组件，默认为 `false`，歌词组件启用后将会开始逐帧更新歌词的动画效果，并对传入的其他参数变更做出反馈。
	 *
	 * 如果禁用了歌词组件动画，你也可以通过引用取得原始渲染组件实例，手动逐帧调用其 `update` 函数来更新动画效果。
	 */
	disabled?: boolean;
	/**
	 * 是否演出部分效果，目前会控制播放间奏点的动画的播放暂停与否，默认为 `true`
	 */
	playing?: boolean;
	/**
	 * 设置歌词行的对齐方式，如果为 `undefined` 则默认为 `center`
	 *
	 * - 设置成 `top` 的话将会向目标歌词行的顶部对齐
	 * - 设置成 `bottom` 的话将会向目标歌词行的底部对齐
	 * - 设置成 `center` 的话将会向目标歌词行的垂直中心对齐
	 */
	alignAnchor?: "top" | "bottom" | "center";
	/**
	 * 设置默认的歌词行对齐位置，相对于整个歌词播放组件的大小位置，如果为 `undefined`
	 * 则默认为 `0.5`
	 *
	 * 可以设置一个 `[0.0-1.0]` 之间的任意数字，代表组件高度由上到下的比例位置
	 */
	alignPosition?: number;
	/**
	 * 设置是否使用物理弹簧算法实现歌词动画效果，默认启用
	 *
	 * 如果启用，则会通过弹簧算法实时处理歌词位置，但是需要性能足够强劲的电脑方可流畅运行
	 *
	 * 如果不启用，则会回退到基于 `transition` 的过渡效果，对低性能的机器比较友好，但是效果会比较单一
	 */
	enableSpring?: boolean;
	/**
	 * 设置是否启用歌词行的模糊效果，默认为 `true`
	 */
	enableBlur?: boolean;
	/**
	 * 设置是否使用物理弹簧算法实现歌词动画效果，默认启用
	 *
	 * 如果启用，则会通过弹簧算法实时处理歌词位置，但是需要性能足够强劲的电脑方可流畅运行
	 *
	 * 如果不启用，则会回退到基于 `transition` 的过渡效果，对低性能的机器比较友好，但是效果会比较单一
	 */
	enableScale?: boolean;
	/**
	 * 设置是否隐藏已经播放过的歌词行，默认不隐藏
	 */
	hidePassedLines?: boolean;
	/**
	 * 设置当前播放歌词，要注意传入后这个数组内的信息不得修改，否则会发生错误
	 */
	lyricLines?: LyricLine[];
	/**
	 * 设置当前播放进度，单位为毫秒且**必须是整数**，此时将会更新内部的歌词进度信息
	 * 内部会根据调用间隔和播放进度自动决定如何滚动和显示歌词，所以这个的调用频率越快越准确越好
	 */
	currentTime?: number;
	isSeeking?: boolean;

	/**
	 * 设置是否应用提前歌词行时序，默认为 `true`
	 */
	enableLyricAdvanceDynamicLyricTime?: boolean;
	/**
	 * 设置所有歌词行在横坐标上的弹簧属性，包括重量、弹力和阻力。
	 *
	 * @param params 需要设置的弹簧属性，提供的属性将会覆盖原来的属性，未提供的属性将会保持原样
	 */
	linePosXSpringParams?: Partial<spring.SpringParams>;
	/**
	 * 设置所有歌词行在​纵坐标上的弹簧属性，包括重量、弹力和阻力。
	 *
	 * @param params 需要设置的弹簧属性，提供的属性将会覆盖原来的属性，未提供的属性将会保持原样
	 */
	linePosYSpringParams?: Partial<spring.SpringParams>;
	/**
	 * 设置所有歌词行在​缩放大小上的弹簧属性，包括重量、弹力和阻力。
	 *
	 * @param params 需要设置的弹簧属性，提供的属性将会覆盖原来的属性，未提供的属性将会保持原样
	 */
	lineScaleSpringParams?: Partial<spring.SpringParams>;
	/**
	 * 在一个特殊的底栏元素内加入指定元素，默认是空白的，可以往内部添加任意元素
	 *
	 * 这个元素始终在歌词的底部，可以用于显示歌曲创作者等信息
	 */
	bottomLine?: ReactNode;
	/**
	 * 当某个歌词行被左键点击时触发的事件
	 * @param line 歌词行的事件对象，可以访问到对应的歌词行信息和歌词行索引
	 */
	onLyricLineClick?: (line: LyricLineMouseEvent) => void;
	/**
	 * 当某个歌词行被右键点击时触发的事件
	 * @param line 歌词行的事件对象，可以访问到对应的歌词行信息和歌词行索引
	 */
	onLyricLineContextMenu?: (line: LyricLineMouseEvent) => void;
}

/**
 * 歌词播放组件的引用
 */
export interface LyricPlayerRef {
	/**
	 * 歌词播放实例
	 */
	lyricPlayer?: CoreLyricPlayer;
	/**
	 * 将歌词播放实例的元素包裹起来的 DIV 元素实例
	 */
	wrapperEl: HTMLDivElement | null;
}

/**
 * 歌词播放组件，本框架的核心组件
 *
 * 尽可能贴切 Apple Music for iPad 的歌词效果设计，且做了力所能及的优化措施
 */
export const LyricPlayer = forwardRef<
	LyricPlayerRef,
	HTMLProps<HTMLDivElement> & LyricPlayerProps
>(
	(
		{
			disabled,
			playing,
			alignAnchor,
			alignPosition,
			enableSpring,
			enableBlur,
			enableScale,
			hidePassedLines,
			lyricLines,
			currentTime,
			isSeeking,
			enableLyricAdvanceDynamicLyricTime,
			linePosXSpringParams,
			linePosYSpringParams,
			lineScaleSpringParams,
			bottomLine,
			onLyricLineClick,
			onLyricLineContextMenu,
			...props
		},
		ref,
	) => {
		const corePlayerRef = useRef<CoreLyricPlayer>();
		const wrapperRef = useRef<HTMLDivElement>(null);

		useEffect(() => {
			corePlayerRef.current = new CoreLyricPlayer();
			return () => {
				corePlayerRef.current?.dispose();
			};
		}, []);

		useEffect(() => {
			if (!disabled) {
				let canceled = false;
				let lastTime = -1;
				const onFrame = (time: number) => {
					if (canceled) return;
					if (lastTime === -1) {
						lastTime = time;
					}
					corePlayerRef.current?.update(time - lastTime);
					lastTime = time;
					requestAnimationFrame(onFrame);
				};
				requestAnimationFrame(onFrame);
				return () => {
					canceled = true;
				};
			}
		}, [disabled]);

		useEffect(() => {
			if (playing !== undefined) {
				if (playing) {
					corePlayerRef.current?.resume();
				} else {
					corePlayerRef.current?.pause();
				}
			} else corePlayerRef.current?.resume();
		}, [playing]);

		useEffect(() => {
			if (corePlayerRef.current)
				wrapperRef.current?.appendChild(corePlayerRef.current.getElement());
		}, [wrapperRef.current]);

		useEffect(() => {
			if (alignAnchor !== undefined)
				corePlayerRef.current?.setAlignAnchor(alignAnchor);
		}, [alignAnchor]);

		useEffect(() => {
			if (hidePassedLines !== undefined)
				corePlayerRef.current?.setHidePassedLines(hidePassedLines);
		}, [hidePassedLines]);

		useEffect(() => {
			if (alignPosition !== undefined)
				corePlayerRef.current?.setAlignPosition(alignPosition);
		}, [alignPosition]);

		useEffect(() => {
			if (enableSpring !== undefined)
				corePlayerRef.current?.setEnableSpring(enableSpring);
			else corePlayerRef.current?.setEnableSpring(true);
		}, [enableSpring]);

		useEffect(() => {
			if (enableScale !== undefined)
				corePlayerRef.current?.setEnableScale(enableScale);
			else corePlayerRef.current?.setEnableScale(true);
		}, [enableScale]);

		useEffect(() => {
			corePlayerRef.current?.setEnableBlur(enableBlur ?? true);
		}, [enableBlur]);

		useEffect(() => {
			corePlayerRef.current?.setLyricAdvanceDynamicLyricTime(enableLyricAdvanceDynamicLyricTime ?? true);
		}, [enableLyricAdvanceDynamicLyricTime]);

		useEffect(() => {
			if (lyricLines !== undefined) {
				corePlayerRef.current?.setLyricLines(lyricLines);
				corePlayerRef.current?.update();
			} else {
				corePlayerRef.current?.setLyricLines([]);
				corePlayerRef.current?.update();
			}
		}, [lyricLines]);

		useEffect(() => {
			if (currentTime !== undefined)
				corePlayerRef.current?.setCurrentTime(currentTime);
			else corePlayerRef.current?.setCurrentTime(0);
		}, [currentTime]);

		useEffect(() => {
			corePlayerRef.current?.setIsSeeking(isSeeking);
		}, [isSeeking]);

		useEffect(() => {
			if (linePosXSpringParams !== undefined)
				corePlayerRef.current?.setLinePosXSpringParams(linePosXSpringParams);
		}, [linePosXSpringParams]);

		useEffect(() => {
			if (linePosYSpringParams !== undefined)
				corePlayerRef.current?.setLinePosYSpringParams(linePosYSpringParams);
		}, [linePosYSpringParams]);

		useEffect(() => {
			if (lineScaleSpringParams !== undefined)
				corePlayerRef.current?.setLineScaleSpringParams(lineScaleSpringParams);
		}, [lineScaleSpringParams]);

		useEffect(() => {
			if (onLyricLineClick) {
				const handler = (e: Event) =>
					onLyricLineClick(e as LyricLineMouseEvent);
				corePlayerRef.current?.addEventListener("line-click", handler);
				return () =>
					corePlayerRef.current?.removeEventListener("line-click", handler);
			}
		}, [onLyricLineClick]);

		useEffect(() => {
			if (onLyricLineContextMenu) {
				const handler = (e: Event) =>
					onLyricLineContextMenu(e as LyricLineMouseEvent);
				corePlayerRef.current?.addEventListener("line-contextmenu", handler);
				return () =>
					corePlayerRef.current?.removeEventListener(
						"line-contextmenu",
						handler,
					);
			}
		}, [onLyricLineContextMenu]);

		useImperativeHandle(
			ref,
			() => ({
				wrapperEl: wrapperRef.current,
				lyricPlayer: corePlayerRef.current,
			}),
			[wrapperRef.current, corePlayerRef.current],
		);

		return (
			<>
				<div {...props} ref={wrapperRef} />
				{corePlayerRef.current?.getBottomLineElement() && bottomLine
					? createPortal(
						bottomLine,
						corePlayerRef.current?.getBottomLineElement(),
					)
					: null}
			</>
		);
	},
);

// packages/vue/src/LyricPlayer.vue
<template>
    <div ref="wrapperRef" v-bind="$attrs"></div>
    <Teleport v-if="playerRef?.getBottomLineElement() && props.bottomLine" :to="playerRef?.getBottomLineElement()" />
</template>

<script setup lang="ts">
import { LyricPlayer, type LyricLineMouseEvent } from "@applemusic-like-lyrics/core";
import { onMounted, onUnmounted, ref, watchEffect } from "vue";
import type { LyricPlayerProps, LyricPlayerEmits, LyricPlayerRef } from ".";

defineOptions({
    inheritAttrs: false,
});

const props = defineProps<LyricPlayerProps>();
const emits = defineEmits<LyricPlayerEmits>();
const wrapperRef = ref<HTMLDivElement>();
const playerRef = ref<LyricPlayer>();

const lineClickHandler = (e: Event) =>
    emits("line-click", e as LyricLineMouseEvent);
const lineContextMenuHandler = (e: Event) =>
    emits("line-contextmenu", e as LyricLineMouseEvent);

onMounted(() => {
    if (wrapperRef.value) {
        playerRef.value = new LyricPlayer();
        wrapperRef.value.appendChild(playerRef.value.getElement());
        playerRef.value.addEventListener("line-click", lineClickHandler);
        playerRef.value.addEventListener("line-contextmenu", lineContextMenuHandler);
    }
});

onUnmounted(() => {
    if (playerRef.value) {
        playerRef.value.removeEventListener("line-click", lineClickHandler);
        playerRef.value.removeEventListener("line-contextmenu", lineContextMenuHandler);
        playerRef.value.dispose();
    }
});

watchEffect((onCleanup) => {
    if (!props.disabled) {
        let canceled = false;
        let lastTime = -1;
        const onFrame = (time: number) => {
            if (canceled) return;
            if (lastTime === -1) {
                lastTime = time;
            }
            playerRef.value?.update(time - lastTime);
            lastTime = time;
            requestAnimationFrame(onFrame);
        };
        requestAnimationFrame(onFrame);
        onCleanup(() => {
            canceled = true;
        });
    }
});

watchEffect(() => {
    if (props.playing !== undefined) {
        if (props.playing) {
            playerRef.value?.resume();
        } else {
            playerRef.value?.pause();
        }
    } else playerRef.value?.resume();
});

watchEffect(() => {
    if (props.alignAnchor !== undefined)
        playerRef.value?.setAlignAnchor(props.alignAnchor);
});

watchEffect(() => {
    if (props.hidePassedLines !== undefined)
        playerRef.value?.setHidePassedLines(props.hidePassedLines);
});

watchEffect(() => {
    if (props.alignPosition !== undefined)
        playerRef.value?.setAlignPosition(props.alignPosition);
});

watchEffect(() => {
    if (props.enableSpring !== undefined)
        playerRef.value?.setEnableSpring(props.enableSpring);
    else
        playerRef.value?.setEnableSpring(true);
});

watchEffect(() => {
    if (props.enableBlur !== undefined)
        playerRef.value?.setEnableBlur(props.enableBlur);
    else
        playerRef.value?.setEnableBlur(true);
});

watchEffect(() => {
    if (props.enableScale !== undefined)
        playerRef.value?.setEnableScale(props.enableScale);
    else
        playerRef.value?.setEnableScale(true);
});

watchEffect(() => {
    if (props.lyricLines !== undefined)
        playerRef.value?.setLyricLines(props.lyricLines);
});

watchEffect(() => {
    if (props.currentTime !== undefined)
        playerRef.value?.setCurrentTime(props.currentTime);
});

watchEffect(() => {
    if (props.linePosXSpringParams !== undefined)
        playerRef.value?.setLinePosXSpringParams(props.linePosXSpringParams);
});

watchEffect(() => {
    if (props.linePosYSpringParams !== undefined)
        playerRef.value?.setLinePosYSpringParams(props.linePosYSpringParams);
});

watchEffect(() => {
    if (props.lineScaleSpringParams !== undefined)
        playerRef.value?.setLineScaleSpringParams(props.lineScaleSpringParams);
});

defineExpose<LyricPlayerRef>({
    lyricPlayer: playerRef,
    wrapperEl: wrapperRef,
});

</script>
